### ISSUE TITLE
Difference in normalized entity between java and dot net versions

### ISSUE THREAD

**Issue by siddhupiddu** [sergey-tihon/Stanford.NLP.NET#56]
I try this using jar files:

java -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators "tokenize,ssplit,pos,lemma,ner"
> Two thousand and one hundred only

The normalized named entity is correctly mapped to 2100. 

THen I try the c# example here : 
https://sergey-tihon.github.io/Stanford.NLP.NET/StanfordCoreNLP.html

I get 100000 as the normalized named entity.

Any help is appreciated :)

**Comment by siddhupiddu** [comment]
Ping!

**Comment by sergey-tihon** [comment]
This happened because NER by default uses SUTime that identify it like a `Date`

You can see it here - http://corenlp.run/
![image](https://cloud.githubusercontent.com/assets/1197905/21635040/5b3bd03a-d26c-11e6-9281-0408e7733cf9.png)

Most probably SUTime do this - http://nlp.stanford.edu:8080/sutime/process
![image](https://cloud.githubusercontent.com/assets/1197905/21635065/8a264a6a-d26c-11e6-9989-4b11660323ff.png)

In C# sample `SUTime` is turned off, that why you do not get correct `NormalizedNamedEntityTag` value:
```csharp
props.setProperty("ner.useSUTime", "0");
```

**Comment by siddhupiddu** [comment]
Thanks. This is awesome.
