### ISSUE TITLE
How do I do a new build?

### ISSUE THREAD

**Issue by pburrows** [sergey-tihon/Stanford.NLP.NET#57]
There are some very recent changes in the CoreNLP project that I would like to use (they were just made yesterday). 

So I:
    got the latest java source and built a new stanford-corenlp.jar file.
    got the latest source of this project and did a normal build (bunch of failing unit tests by the way).
    replaced the existing stanford-corenlp-3.7.0.jar from the normal build with the new one I just built.
    ran build.cmd again.

This seems like it worked. 

Other than the caveat that I am using a "daily build" and not an official release, is there anything wrong with this plan?

**Comment by sergey-tihon** [comment]
Hi,

All test should be green on these commit
https://github.com/sergey-tihon/Stanford.NLP.NET/tree/edbef331160253b2db786155fe669cb50c32573c

the `master` has problem on unzipping `jar` with models (because it contains files with invalid names for win) - https://github.com/stanfordnlp/CoreNLP/issues/293

Manual step: unzip `\paket-files\nlp.stanford.edu\stanford-corenlp-full-2016-10-31\stanford-corenlp-3.7.0-models.jar` to `\paket-files\nlp.stanford.edu\stanford-corenlp-full-2016-10-31\models\` 

other steps are correct

**Comment by sergey-tihon** [comment]
Build is green now, so no manual steps are required - https://ci.appveyor.com/project/sergey-tihon/stanford-nlp-net/build/0.0.1.60

**Comment by pburrows** [comment]
Hey thanks, I'll try it out. Wound up setting up a Java dev environment to try out the fix and I couldn't get it to work there either. So I think more work needs to be done anyway (or my understanding needs to expand). Here's the issue at CoreNLP if it matters: https://github.com/stanfordnlp/CoreNLP/issues/338

Again, thanks for your response!

**Comment by pburrows** [comment]
I was able to pull the latest CoreNLP and make a new build. Thanks for your help!
